# permissions for end users to view githubissues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubissue-viewer-role
rules:
- apiGroups:
  - example.training.redhat.com
  resources:
  - githubissues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.training.redhat.com
  resources:
  - githubissues/status
  verbs:
  - get
