apiVersion: example.training.redhat.com/v1alpha1
kind: GitHubIssue
metadata:
  name: github-issue-sample3
spec:
  repo: arielireni/Issues-Example
  title: issue after code review
  description: with edit
